version: '3.7'

services:

  app:
    container_name: app-modop
    build:
      context: modop_v1
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    